### ISSUE TITLE
Java Error, Docker, RPi4 4GB, Ubuntu Server 20.04.3 LTS

### ISSUE THREAD

**Issue by CharlieEcho** [wwadge/awair-bridge#4]
Docker
RPi4 4GB
Ubuntu Server 20.04.3 LTS

Only 1/4 Awair devices was read and updated on PW explorer Sensor. See error from Docker log:

```
2022-04-04 22:17:48.672 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at com.pw.awairbridge.service.impl.DataBridgeImpl.runService(DataBridgeImpl.java:90) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar:5.3.18]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

Any ideas?

VBR,
CE

**Comment by wwadge** [comment]
Give me a longer log please, Awair sent something different than usual for your case

**Comment by CharlieEcho** [comment]
This message is repeated in the docker log (from Portainer), so I only copied the latest iteration. It here a way to turn up the debug log on the docker image?


```
2022-04-04 22:19:33.760  INFO 1 --- [   scheduling-1] com.pw.awairbridge.util.PWAuthService    : Logging in PW
2022-04-04 22:19:35.334  INFO 1 --- [   scheduling-1] com.pw.awairbridge.util.PWAuthService    : Login to PW: OK
2022-04-04 22:32:48.673  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : Starting data fetch...
2022-04-04 22:32:49.333  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : AwairDataPacket(otherFields={data=[{timestamp=2022-04-04T22:32:48.000Z, score=78.0, sensors=[{comp=humid, value=63.56999969482422}, {comp=voc, value=113.0}, {comp=temp, value=29.170000076293945}, {comp=pm25, value=6.0}, {comp=co2, value=445.0}], indices=[{comp=co2, value=0.0}, {comp=temp, value=2.0}, {comp=humid, value=2.0}, {comp=voc, value=0.0}, {comp=pm25, value=0.0}]}]})
2022-04-04 22:32:50.454  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : Sending data for device 'RR2' to PW: OK
2022-04-04 22:33:00.889  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : AwairDataPacket(otherFields={data=[]})
2022-04-04 22:33:00.892 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at com.pw.awairbridge.service.impl.DataBridgeImpl.runService(DataBridgeImpl.java:90) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar:5.3.18]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by aseelert** [comment]
Running Synology DS918 (intel)
and Docker

same for me 3 out of 5 are working (1 which is up and running get the error) and 1 is disconnected in Awair app.


022-04-05 08:07:35.901  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : Sending data for device 'Abteiweg Element' to PW: OK
2022-04-05 08:07:37.221  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : AwairDataPacket(otherFields={data=[]})
2022-04-05 08:07:37.234 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:359) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at com.pw.awairbridge.service.impl.DataBridgeImpl.runService(DataBridgeImpl.java:90) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar:5.3.18]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by wwadge** [comment]
"AwairDataPacket(otherFields={data=[]})"  --> Awair returned no data and app was always expecting data. I added a check to not crash out so pull latest image and try with that (but of course, no data to send to PW either since none received).

PS for logs, append "--debug" to the docker command line  : docker run ... wwadge/awair-bridge --debug

**Comment by aseelert** [comment]
> "AwairDataPacket(otherFields={data=[]})" --> Awair returned no data and app was always expecting data. I added a check to not crash out so pull latest image and try with that (but of course, no data to send to PW either since none received).
> 
> PS for logs, append "--debug" to the docker command line : docker run ... wwadge/awair-bridge --debug

logs good now, thank you very much.

p, value=22.700000762939453}, {comp=voc, value=492.0}, {comp=humid, value=40.0}], indices=[{comp=voc, value=1.0}, {comp=temp, value=0.0}, {comp=co2, value=1.0}, {comp=humid, value=0.0}, {comp=pm25, value=2.0}]}]})
2022-04-05 08:39:13.621  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : Sending data for device 'Abteiweg Element' to PW: OK
2022-04-05 08:39:24.031  INFO 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : AwairDataPacket(otherFields={data=[]})
2022-04-05 08:39:24.032  WARN 1 --- [   scheduling-1] c.p.a.service.impl.DataBridgeImpl        : Did not receive data as expected from Awair, skipping 'Hofsee'

**Comment by aseelert** [comment]
as you may know, lot of people (such as myself) got the Awair broken during the last update and waiting for a fix. But now your code is covering the Awair issue too. I thank you very much for this!!!
